//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIY_v2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
            this.ProductReply = new HashSet<ProductReply>();
            this.TaskerComment = new HashSet<TaskerComment>();
            this.Orders = new HashSet<Orders>();
        }
        [DisplayName("會員ID")]
        public int MemberID { get; set; }
        [DisplayName("會員帳號")]
        public string MemberAccount { get; set; }
        [DisplayName("會員密碼")]
        public string MemberPwd { get; set; }
        [DisplayName("會員姓名")]
        public string MemberName { get; set; }
        [DisplayName("會員性別")]
        public string MemberGender { get; set; }
        [DisplayName("會員生日")]
        public System.DateTime MemberBirthday { get; set; }
        [DisplayName("會員暱稱")]
        public string MemberNickname { get; set; }
        [DisplayName("會員信箱")]
        public string MemberEmail { get; set; }
        [DisplayName("會員地址")]
        public string MemberAddress { get; set; }
        [DisplayName("會員手機")]
        public string MemberPhone { get; set; }
        [DisplayName("會員權限")]
        public string Permission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReply> ProductReply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskerComment> TaskerComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
