//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIY_v2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order_Detail
    {
        [DisplayName("流水號")]
        public int SerialNumber { get; set; }

        [DisplayName("訂單日期")]
        public System.DateTime OrderDate { get; set; }

        [DisplayName("訂單編號")]
        public string OrderID { get; set; }
        
        [DisplayName("會員編號")]
        public Nullable<int> MemberID { get; set; }

        [DisplayName("產品編號")]
        public string ProductID { get; set; }

        [DisplayName("產品名稱")]
        public string ProductName { get; set; }

        [DisplayName("產品單價")]
        public Nullable<short> ProductPrice { get; set; }

        [DisplayName("訂購數量")]
        public Nullable<short> OrderQuantity { get; set; }

        [DisplayName("訂單狀態")]
        public string OrderStatus { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Product Product { get; set; }
    }
}
