//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIY_v2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TaskerComment
    {
        [DisplayName("留言編號")]
        public int ReplyID { get; set; }

        [DisplayName("師傅編號")]
        public Nullable<int> TaskerID { get; set; }

        [DisplayName("會員編號")]
        public Nullable<int> MemberID { get; set; }

        [DisplayName("師傅帳號")]
        public string MemberAccount { get; set; }

        [DisplayName("評論內容")]
        [StringLength(500, ErrorMessage = "評論內容請控制在500個字以內")]
        public string Comment { get; set; }

        [DisplayName("留言時間")]
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> Star { get; set; }

        [DisplayName("留言帳號")]
        public virtual Member Member { get; set; }
        public virtual Tasker Tasker { get; set; }
    }
}
