//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIY_v2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TaskerService
    {
        [DisplayName("師傅編號")]
        [Required]
        public int TaskerID { get; set; }

        [DisplayName("服務類別編號")]
        [Required(ErrorMessage = "請選取服務類別")]
        public string ServiceCategoryID { get; set; }

        [DisplayName("服務類別")]
        [Required(ErrorMessage = "請選取服務類別")]
        public string ServiceCategory { get; set; }
    
        public virtual Tasker Tasker { get; set; }
    }
}
